apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pod-mgr
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["create", "get", "list", "delete", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: lich-pod-mgr
subjects:
  - kind: ServiceAccount
    name: {{ include "lich.serviceAccountName" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pod-mgr
